//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyFloe.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkyFloe.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The compressed stream is corrupt.
        /// </summary>
        internal static string CompressionInvalidData {
            get {
                return ResourceManager.GetString("CompressionInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The engine is already connected to a backup archive.
        /// </summary>
        internal static string ConnectionAlreadyConnected {
            get {
                return ResourceManager.GetString("ConnectionAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the specified backup store.
        /// </summary>
        internal static string ConnectionConnectFailed {
            get {
                return ResourceManager.GetString("ConnectionConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string property {0} was not found in the store type.
        /// </summary>
        internal static string ConnectionInvalidProperty {
            get {
                return ResourceManager.GetString("ConnectionInvalidProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The engine is not connected to a backup store.
        /// </summary>
        internal static string ConnectionNotConnected {
            get {
                return ResourceManager.GetString("ConnectionNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new backup session cannot be created because a backup session is already in progress.
        /// </summary>
        internal static string CreateBackupSessionExists {
            get {
                return ResourceManager.GetString("CreateBackupSessionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path {0} is not a directory.
        /// </summary>
        internal static string CreateBackupSourcePathNotADirectory {
            get {
                return ResourceManager.GetString("CreateBackupSourcePathNotADirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The source path {0} was not found in the file system.
        /// </summary>
        internal static string CreateBackupSourcePathNotFound {
            get {
                return ResourceManager.GetString("CreateBackupSourcePathNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive {0} already exists in the backup store.
        /// </summary>
        internal static string EngineArchiveExists {
            get {
                return ResourceManager.GetString("EngineArchiveExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The archive {0} was not found in the backup store.
        /// </summary>
        internal static string EngineArchiveNotFound {
            get {
                return ResourceManager.GetString("EngineArchiveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified archive credentials are invalid.
        /// </summary>
        internal static string EngineAuthenticationFailed {
            get {
                return ResourceManager.GetString("EngineAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} was restored, but its CRC value did not match the archive metadata.
        /// </summary>
        internal static string ExecuteRestoreCrcFailed {
            get {
                return ResourceManager.GetString("ExecuteRestoreCrcFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation failed because the stream stack is empty.
        /// </summary>
        internal static string StreamStackEmpty {
            get {
                return ResourceManager.GetString("StreamStackEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current task has already executed and cannot be run again.
        /// </summary>
        internal static string TaskAlreadyExecuted {
            get {
                return ResourceManager.GetString("TaskAlreadyExecuted", resourceCulture);
            }
        }
    }
}
